; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32 @ ^6.7.0
board = esp32-s3-devkitc-1
framework = arduino

board_upload.flash_size = 16MB
board_build.arduino.memory_type = qio_opi

; ✅ primero “desdefinimos” cualquier ARDUINO_USB_MODE que venga del board
build_unflags =
  -DARDUINO_USB_MODE

build_flags =
  -DBOARD_HAS_PSRAM
  -DARDUINO_USB_MODE=0            ; UART (mismo COM del upload)
  -DCORE_DEBUG_LEVEL=5
  -DCAM_XCLK_FREQ=20000000
  -DCAM_XCLK_GPIO=15
  -Iinclude                       ; ✅ forzamos a incluir la carpeta include/

monitor_speed = 115200
upload_speed = 921600
monitor_filters = esp32_exception_decoder

lib_deps =
  espressif/esp32-camera @ ^2.0.4
